"""Tests for the render-evidence-package Stage-1 markdown renderer.

Verifies:
  - KRAS-COADREAD evidence_package → markdown with expected sections
  - TG-COADREAD (negative control) → refusal page
  - Card panels render with summary + interpretation_call + caveats
  - Modality fit table renders with per-modality entries
  - Decoupling: renderer works on a fresh evidence_package JSON without
    any orchestrator dependency

Test inputs are HAND-AUTHORED evidence_package fixtures (not generated by
compose_dashboard) so the renderer can be tested independently. This is
also the discipline check that the renderer is genuinely decoupled.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

SCRIPTS_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SCRIPTS_DIR))

from scripts.render_markdown import render_evidence_package  # noqa: E402


# ============================================================================
# Hand-authored evidence_package fixtures
# ============================================================================

def _minimal_kras_coadread_ep() -> dict:
    """Synthetic KRAS-COADREAD evidence_package with 3 cards covering the main
    panel types: pass, passed_with_warnings, excluded_by_applies_when."""
    return {
        "package_id": "ep-kras-coadread-test-pinned-001",
        "framework_version": "2.0.0",
        "generated_at": "2026-06-26T00:00:00Z",
        "generated_by": "skills/compose-dashboard@0a1b2c3",
        "context": {
            "target": {"symbol": "KRAS", "hgnc_id": 6407, "ensembl": "ENSG00000133703.13"},
            "indication": {"oncotree_code": "COADREAD"},
            "subgroup_spec": "all",
            "scope": "cancer_type",
        },
        "governance": {
            "data_mode": "pinned",
            "release_pin": "2026-Q2",
            "lockfile_ref": "lockfile.yaml",
            "validation_summary": {
                "n_cards_attempted": 3,
                "n_cards_passed": 2,
                "n_cards_passed_with_warnings": 1,
                "n_cards_failed": 0,
                "n_cards_excluded_by_applies_when": 1,
            },
        },
        "dashboard_spec_ref": "intracellular-intrinsic-base",
        "cards": [
            {
                "card_id": "expression-tumor-vs-adjacent",
                "card_version": "1.0.0",
                "validation_state": "pass",
                "summary": {"log2_fc": 2.1, "q_value": 0.0003, "n_tumor": 412},
                "interpretation_call": "strong upregulation",
                "caveats": ["RNA does not imply protein"],
                "provenance": {"method_calls": [{"method": "dge-deseq2", "git_sha": "abc123"}],
                               "input_manifest_ids": ["coadread-dge-df06320"]},
            },
            {
                "card_id": "dependency-lineage-selectivity",
                "card_version": "1.0.0",
                "validation_state": "passed_with_warnings",
                "summary": {"median_chronos_lineage": -0.95, "n_cell_lines_in_lineage": 38},
                "interpretation_call": "strong selective dependency",
                "warning_ids": ["small_lineage_panel"],
                "caveats": [],
                "provenance": {"method_calls": [], "input_manifest_ids": []},
            },
            {
                "card_id": "normal-tissue-liability",
                "card_version": "1.0.0",
                "excluded_by_applies_when": True,
                "exclusion_reason": "card data_status='data_blocked': HPA mirror not yet built",
            },
        ],
        "synthesis": {
            "headline": "For KRAS in COADREAD, small_molecule fit is strong. Strongest evidence: tractable target.",
            "caveats_summary": "Normal-tissue-liability card excluded (HPA data blocked).",
            "modality_fit_assessment": [
                {
                    "modality": "small_molecule",
                    "fit_level": "strong",
                    "headline_decision_question": "Is this target functionally required and pharmacologically tractable?",
                    "primary_cards_positive_count": 2,
                    "primary_cards_in_scope": 2,
                    "killer_conditions_hit": [],
                    "rationale": "2/2 primary cards positive",
                },
                {
                    "modality": "degrader",
                    "fit_level": "moderate",
                    "headline_decision_question": "Is this protein expressed, ligandable, and degradable?",
                    "primary_cards_positive_count": 1,
                    "primary_cards_in_scope": 2,
                    "killer_conditions_hit": [],
                    "rationale": "1/2 primary cards positive",
                },
            ],
        },
        "renderings": {"markdown": "renderings/dashboard.md"},
        "schema_version": 1,
    }


def _tg_unknown_axis_ep() -> dict:
    """TG-COADREAD negative-control evidence_package: empty cards, refusal synthesis."""
    return {
        "package_id": "ep-tg-coadread-test-pinned-001",
        "framework_version": "2.0.0",
        "generated_at": "2026-06-26T00:00:00Z",
        "generated_by": "skills/compose-dashboard@0a1b2c3",
        "context": {
            "target": {"symbol": "TG", "hgnc_id": 1},
            "indication": {"oncotree_code": "COADREAD"},
            "subgroup_spec": "all",
            "scope": "cancer_type",
        },
        "governance": {
            "data_mode": "pinned",
            "release_pin": "2026-Q2",
            "lockfile_ref": "lockfile.yaml",
            "validation_summary": {
                "n_cards_attempted": 0,
                "n_cards_passed": 0,
                "n_cards_passed_with_warnings": 0,
                "n_cards_failed": 0,
                "n_cards_excluded_by_applies_when": 0,
            },
        },
        "dashboard_spec_ref": "unresolved",
        "cards": [],
        "synthesis": {
            "headline": "Framework cannot evaluate TG in COADREAD: target not in lookup. Add a curated axis assignment.",
            "caveats_summary": "Target 'TG' is not in target_biology_axis_lookup.yaml.",
            "modality_fit_assessment": [],
        },
        "renderings": {"markdown": "renderings/dashboard.md"},
        "schema_version": 1,
    }


# ============================================================================
# Test 1: KRAS-COADREAD renders with all expected sections
# ============================================================================

def test_render_kras_coadread_full_dashboard():
    md = render_evidence_package(_minimal_kras_coadread_ep())

    # Title
    assert "# Evidence Package: KRAS in COADREAD" in md

    # Executive summary
    assert "## Executive Summary" in md
    assert "small_molecule fit is strong" in md

    # Modality fit table
    assert "## Modality Fit Assessment" in md
    assert "| Modality | Fit |" in md
    assert "small_molecule" in md
    assert "degrader" in md

    # Decision questions
    assert "### Decision Questions Asked" in md

    # Governance
    assert "## Governance" in md
    assert "**Data mode**: `pinned`" in md
    assert "Validation Summary" in md

    # Card evidence
    assert "## Card Evidence" in md
    assert "expression-tumor-vs-adjacent" in md
    assert "dependency-lineage-selectivity" in md
    assert "normal-tissue-liability" in md  # excluded but still listed

    # Provenance footer
    assert "## Provenance Footer" in md


# ============================================================================
# Test 2: TG-COADREAD renders the refusal page
# ============================================================================

def test_render_tg_coadread_refusal_page():
    md = render_evidence_package(_tg_unknown_axis_ep())

    # Title
    assert "# Evidence Package: TG in COADREAD" in md

    # Refusal indicator
    assert "Framework Refused to Evaluate" in md

    # Refusal reason
    assert "TG" in md
    assert "lookup" in md.lower()

    # Next-steps actionable
    assert "Next Steps" in md

    # No card panels
    assert "## Card Evidence" not in md
    # No modality fit assessment
    assert "## Modality Fit Assessment" not in md

    # Governance still present
    assert "## Governance" in md


# ============================================================================
# Test 3: Modality fit table uses icons
# ============================================================================

def test_render_modality_fit_table_uses_icons():
    md = render_evidence_package(_minimal_kras_coadread_ep())
    has_icon = any(icon in md for icon in ["🟢", "🟡", "🟠", "🔴", "⚪"])
    assert has_icon, "modality fit table should display status icons"


# ============================================================================
# Test 4: Decoupling — render handles JSON-serialized round-trip
# ============================================================================

def test_renderer_decoupled_works_after_json_roundtrip(tmp_path):
    ep = _minimal_kras_coadread_ep()
    # Write + read to simulate persistence
    ep_file = tmp_path / "ep.json"
    ep_file.write_text(json.dumps(ep, default=str))
    ep_reloaded = json.loads(ep_file.read_text())

    md = render_evidence_package(ep_reloaded)
    assert "# Evidence Package: KRAS in COADREAD" in md
    assert "Executive Summary" in md


# ============================================================================
# Test 5: Pass cards get ✓; warned cards get ⚠; excluded get ⏸️
# ============================================================================

def test_render_card_state_icons():
    md = render_evidence_package(_minimal_kras_coadread_ep())
    assert "✓ `expression-tumor-vs-adjacent`" in md, "passed card should have ✓ icon"
    assert "⚠ `dependency-lineage-selectivity`" in md, "warned card should have ⚠ icon"
    assert "⏸️ `normal-tissue-liability`" in md, "excluded card should have ⏸️ icon"


# ============================================================================
# Test 6: Warning IDs surface in rendered card
# ============================================================================

def test_render_warning_ids_surface():
    md = render_evidence_package(_minimal_kras_coadread_ep())
    assert "small_lineage_panel" in md


# ============================================================================
# Test 7: Excluded card renders exclusion_reason
# ============================================================================

def test_render_excluded_card_shows_reason():
    md = render_evidence_package(_minimal_kras_coadread_ep())
    assert "data_blocked" in md
    assert "HPA" in md


# ============================================================================
# Test 8: Subgroup-panorama table renders the evidence_state trichotomy
# ============================================================================

def _panorama_rows():
    return [
        {"stratum": "MSS", "class": "strong_dependency", "evidence_state": "measured",
         "median_chronos": -1.22, "subgroup_n": 71, "subgroup_n_floor_met": True,
         "source_cohort": "DepMap-26Q1"},
        {"stratum": "MSI_H", "class": "moderate_dependency", "evidence_state": "underpowered",
         "median_chronos": -0.69, "subgroup_n": 17, "subgroup_n_floor_met": False,
         "source_cohort": "DepMap-26Q1"},
        {"stratum": "POLE", "class": "insufficient", "evidence_state": "absent",
         "median_chronos": None, "subgroup_n": 0, "subgroup_n_floor_met": False,
         "source_cohort": "DepMap-26Q1"},
    ]


def test_panorama_table_distinguishes_evidence_states():
    from scripts.render_markdown import _render_subgroup_panorama_table
    lines = _render_subgroup_panorama_table(_panorama_rows())
    md = "\n".join(lines)
    # measured is trusted; underpowered is flagged inline with n<floor; absent is marked.
    assert "● measured" in md
    assert "◐ underpowered (n=17<30)" in md, "underpowered row must flag n vs floor inline"
    assert "○ absent" in md
    # stratum + evidence_state pinned as the first two columns.
    header = lines[0]
    assert header.index("stratum") < header.index("evidence_state")
    assert header.index("evidence_state") < header.index("class")
    # legend states the admissibility rule.
    assert "inadmissible in comparative claims" in md


def test_panorama_field_routes_to_trichotomy_renderer_not_generic():
    """A card whose summary carries per_subgroup_metrics gets the evidence_state
    renderer (badges), not the plain list-of-dicts table."""
    from scripts.render_markdown import _render_card_panel
    card = {
        "card_id": "subgroup-stratified-dependency",
        "interpretation_call": "subgroup-specific dependency pattern",
        "validation_state": "pass",
        "summary": {"per_subgroup_metrics": _panorama_rows(), "n_subgroups_with_data": 3},
        "caveats": [],
    }
    md = "\n".join(_render_card_panel(card))
    assert "● measured" in md and "◐ underpowered" in md, "panorama field must use the trichotomy renderer"
