#!/usr/bin/env python3
"""freeze_drift_golden — (re)generate the offline golden-set drift-CI fixtures.

For each golden case (KRAS/COADREAD, MARK2/PAAD) this:
  1. TRIMS the full target-profile evidence_package to the integrator-relevant fields
     (drift_golden.trim_evidence_package) and writes the small fixture.
  2. CAPTURES a real two-call Bedrock response (unless --replay-only) and freezes it as
     llm_replay.json — the LLM PROSE is frozen ONCE here; the drift-CI never calls Bedrock.
  3. Re-runs the integrator OFFLINE from that replay and freezes the DETERMINISTIC SPINE subset
     (drift_golden.deterministic_spine_subset) as expected_spine.json.

The golden is intentionally regenerated by a human on a deliberate prompt/model change (which flips
provenance.prompt_template_hash and so fails test_drift_guard until refrozen + reviewed).

Usage (live capture, needs BEDROCK_AWS_PROFILE=cmp-dev):
  python3 freeze_drift_golden.py --all
  python3 freeze_drift_golden.py --case KRAS-COADREAD \
      --source /tmp/bakeoff-features/KRAS-envfix/evidence_package.json
  python3 freeze_drift_golden.py --all --replay-only    # refreeze expected_spine from frozen replays
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent.parent))  # skills/ (for _skills_common)

import drift_golden as dg  # noqa: E402
import run as R  # noqa: E402

GOLDEN = HERE.parent / "tests" / "fixtures" / "golden"

# case -> (default source evidence_package, objective, modality)
CASES = {
    "KRAS-COADREAD": (
        "/tmp/bakeoff-features/KRAS-envfix/evidence_package.json",
        "small-molecule drug target",
        "small_molecule",
    ),
    "MARK2-PAAD": (
        "/tmp/bakeoff-features/MARK2-PAAD/evidence_package.json",
        "small-molecule drug target",
        "small_molecule",
    ),
}


def _capturing_synth():
    """Wrap the real Bedrock synth; record each call's response by name for replay."""
    real = R._default_synthesize()
    captured: dict = {}

    def _synth(system, user, name, schema, **kw):
        resp = real(system, user, name, schema, **kw)
        captured[name] = resp
        return resp

    return _synth, captured


def freeze_case(case: str, source: str | None, replay_only: bool) -> None:
    src_path, objective, modality = CASES[case]
    source = source or src_path
    outd = GOLDEN / case
    outd.mkdir(parents=True, exist_ok=True)

    # 1. trim + write the small evidence-package fixture (skip if replay-only and it already exists)
    pkg_fix = outd / "evidence_package.json"
    if not (replay_only and pkg_fix.exists()):
        full = json.loads(Path(source).read_text())
        trimmed = dg.trim_evidence_package(full)
        pkg_fix.write_text(json.dumps(trimmed, indent=2, default=str))
        (outd / "meta.json").write_text(
            json.dumps(
                {"case": case, "objective": objective, "modality": modality, "source_evidence_package": source},
                indent=2,
            )
        )
    meta = json.loads((outd / "meta.json").read_text())

    # 2. capture (or reuse) the two-call LLM replay
    replay_fix = outd / "llm_replay.json"
    if replay_only:
        replay = json.loads(replay_fix.read_text())
        synth = R.replay_synthesize(replay)
    else:
        synth, replay = _capturing_synth()

    # run once (live-capture or offline-replay) to drive the pipeline
    r = R.run(
        str(pkg_fix),
        meta.get("risk"),
        meta["objective"],
        meta["modality"],
        meta.get("dossier"),
        synthesize_fn=synth,
        llm_mode="offline_replay",
    )  # spine is frozen as an offline-replay result
    if not replay_only:
        replay_fix.write_text(json.dumps(replay, indent=2, default=str))
        # re-run purely offline from the just-captured replay so the frozen spine matches the
        # exact bytes the drift-CI will replay
        r = R.run(
            str(pkg_fix),
            meta.get("risk"),
            meta["objective"],
            meta["modality"],
            meta.get("dossier"),
            synthesize_fn=R.replay_synthesize(replay),
            llm_mode="offline_replay",
        )

    # 3. freeze the deterministic spine subset
    spine = dg.deterministic_spine_subset(r)
    (outd / "expected_spine.json").write_text(json.dumps(spine, indent=2, default=str))
    print(
        f"[{case}] verdict={spine['computed_verdict']} ceiling={spine['gate_ceiling']} "
        f"traceability={spine['clause_traceability']} certainty={spine['overall_certainty']} "
        f"coherence_viol={spine['n_coherence_violations']} promotable={spine['promotable']}"
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", choices=sorted(CASES))
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--source", default=None, help="override source evidence_package.json")
    ap.add_argument(
        "--replay-only", action="store_true", help="refreeze expected_spine from the EXISTING llm_replay (no Bedrock)"
    )
    args = ap.parse_args(argv)
    cases = sorted(CASES) if args.all else [args.case] if args.case else []
    if not cases:
        ap.error("pass --all or --case <name>")
    for c in cases:
        freeze_case(c, args.source, args.replay_only)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
