#!/usr/bin/env python3
"""freeze_drift_golden — (re)generate the offline golden-set drift-CI fixtures.

For each golden case (see CASES) this:
  1. TRIMS the full target-profile evidence_package to the integrator-relevant fields
     (drift_golden.trim_evidence_package) and writes the small fixture, plus — when the case declares a
     `run_dir` — COPIES that run's chain inputs in beside it (risk.json / dossier.json /
     substrate/<axis>.json), so the case is self-contained and CI never reaches outside the repo.
  2. CAPTURES a real two-call Bedrock response (unless --replay-only) and freezes it as
     llm_replay.json — the LLM PROSE is frozen ONCE here; the drift-CI never calls Bedrock.
  3. Re-runs the integrator OFFLINE from that replay and freezes the DETERMINISTIC SPINE subset
     (drift_golden.deterministic_spine_subset) as expected_spine.json.

Coverage is a property of the SET, not of any one case: two cases that agree on modality and on which
inputs are present freeze the same code path twice. test_golden_set_covers_distinct_paths enforces it.

The golden is intentionally regenerated by a human on a deliberate prompt/model change (which flips
provenance.prompt_template_hash and so fails test_drift_guard until refrozen + reviewed).

Usage (live capture, needs BEDROCK_AWS_PROFILE=cmp-dev):
  python3 freeze_drift_golden.py --all
  python3 freeze_drift_golden.py --case KRAS-COADREAD \
      --source /tmp/bakeoff-features/KRAS-envfix/evidence_package.json
  python3 freeze_drift_golden.py --all --replay-only    # refreeze expected_spine from frozen replays
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent.parent))  # skills/ (for _skills_common)

import drift_golden as dg  # noqa: E402
import run as R  # noqa: E402

GOLDEN = HERE.parent / "tests" / "fixtures" / "golden"

# case -> the freeze spec. `source` is the full evidence_package to trim; `run_dir`, when set, is a
# target-profile run directory the CHAIN inputs are copied out of (risk_assessment.json ->
# risk.json, subskills/target_intrinsic/package.json -> dossier.json, grounded_<axis>.json ->
# substrate/<axis>.json), making the case self-contained and portable — a golden may not reference a
# /tmp path that CI has never seen.
#
# WHY a case with chain inputs: both original cases run the BARE package, so every frozen spine
# carries `degraded inputs: ['dossier']` and a `low` cap ceiling. That made the drift-CI blind to the
# whole degradation-and-dossier path — the same blind spot that let F16 ship inert. NECTIN4-BLCA is
# frozen WITH dossier + risk + substrate, and on `adc`, so modality scoping (immune_context in scope
# for the antibody-derived channels only) and the non-degraded certainty path are both pinned.
CASES = {
    "KRAS-COADREAD": {
        "source": "/tmp/bakeoff-features/KRAS-envfix/evidence_package.json",
        "objective": "small-molecule drug target",
        "modality": "small_molecule",
    },
    "MARK2-PAAD": {
        "source": "/tmp/bakeoff-features/MARK2-PAAD/evidence_package.json",
        "objective": "small-molecule drug target",
        "modality": "small_molecule",
    },
    "NECTIN4-BLCA": {
        "source": None,  # set by --source or run_dir/evidence_package.json
        "run_dir": str(
            Path.home() / "dev" / "framework-runs" / "cross-evidence-hypothesis" / "panel-2026-09-12" / "NECTIN4-BLCA"
        ),
        "objective": "antibody-drug conjugate target",
        "modality": "adc",
    },
}


def _copy_chain_inputs(run_dir: Path, outd: Path) -> dict:
    """Copy a run's chain inputs into the case dir under the names load_golden_case looks for.
    Returns a dict of what was found, for meta.json. Absent inputs are simply not frozen."""
    found: dict = {}
    risk = run_dir / "risk_assessment.json"
    if risk.exists():
        (outd / "risk.json").write_text(risk.read_text())
        found["risk"] = "risk.json"
    dossier = run_dir / "subskills" / "target_intrinsic" / "package.json"
    if dossier.exists():
        (outd / "dossier.json").write_text(dossier.read_text())
        found["dossier"] = "dossier.json"
    axes = sorted(run_dir.glob("grounded_*.json"))
    if axes:
        sub = outd / "substrate"
        sub.mkdir(parents=True, exist_ok=True)
        for p in axes:
            (sub / f"{p.name[len('grounded_') :]}").write_text(p.read_text())
        found["substrate_axes"] = [p.name[len("grounded_") : -len(".json")] for p in axes]
    return found


def _capturing_synth():
    """Wrap the real Bedrock synth; record each call's response by name for replay."""
    real = R._default_synthesize()
    captured: dict = {}

    def _synth(system, user, name, schema, **kw):
        resp = real(system, user, name, schema, **kw)
        captured[name] = resp
        return resp

    return _synth, captured


def freeze_case(case: str, source: str | None, replay_only: bool) -> None:
    spec = CASES[case]
    run_dir = Path(spec["run_dir"]) if spec.get("run_dir") else None
    source = source or spec.get("source") or (str(run_dir / "evidence_package.json") if run_dir else None)
    if not source:
        raise SystemExit(f"[{case}] no source evidence_package (pass --source or set run_dir)")
    outd = GOLDEN / case
    outd.mkdir(parents=True, exist_ok=True)

    # 1. trim + write the small evidence-package fixture (skip if replay-only and it already exists)
    pkg_fix = outd / "evidence_package.json"
    if not (replay_only and pkg_fix.exists()):
        full = json.loads(Path(source).read_text())
        trimmed = dg.trim_evidence_package(full)
        pkg_fix.write_text(json.dumps(trimmed, indent=2, default=str))
        chain = _copy_chain_inputs(run_dir, outd) if run_dir and run_dir.is_dir() else {}
        (outd / "meta.json").write_text(
            json.dumps(
                {
                    "case": case,
                    "objective": spec["objective"],
                    "modality": spec["modality"],
                    "source_evidence_package": source,
                    # a record of which chain inputs this case exercises; load_golden_case discovers the
                    # files by name, so this is documentation for a reviewer, not wiring.
                    "chain_inputs": chain or None,
                },
                indent=2,
            )
        )
    meta = json.loads((outd / "meta.json").read_text())
    # Chain inputs are discovered BY FILENAME, exactly as load_golden_case does at drift-CI time — so a
    # freeze and a drift check cannot disagree about what the case feeds the integrator.
    risk_path = str(outd / "risk.json") if (outd / "risk.json").exists() else None
    dossier_path = str(outd / "dossier.json") if (outd / "dossier.json").exists() else None
    substrate = dg.load_golden_substrate(outd)

    # 2. capture (or reuse) the two-call LLM replay
    replay_fix = outd / "llm_replay.json"
    if replay_only:
        replay = json.loads(replay_fix.read_text())
        synth = R.replay_synthesize(replay)
    else:
        synth, replay = _capturing_synth()

    def _run(synthesize_fn):
        return R.run(
            str(pkg_fix),
            risk_path,
            meta["objective"],
            meta["modality"],
            dossier_path,
            synthesize_fn=synthesize_fn,
            llm_mode="offline_replay",  # spine is frozen as an offline-replay result
            substrate=substrate,
        )

    # run once (live-capture or offline-replay) to drive the pipeline
    r = _run(synth)
    if not replay_only:
        replay_fix.write_text(json.dumps(replay, indent=2, default=str))
        # re-run purely offline from the just-captured replay so the frozen spine matches the
        # exact bytes the drift-CI will replay
        r = _run(R.replay_synthesize(replay))

    # 3. freeze the deterministic spine subset
    spine = dg.deterministic_spine_subset(r)
    (outd / "expected_spine.json").write_text(json.dumps(spine, indent=2, default=str))
    print(
        f"[{case}] modality={meta['modality']} verdict={spine['computed_verdict']} "
        f"ceiling={spine['gate_ceiling']} traceability={spine['clause_traceability']} "
        f"certainty={spine['overall_certainty']} cap_ceiling={spine['cap_ceiling']} "
        f"coherence_viol={spine['n_coherence_violations']} promotable={spine['promotable']}"
    )
    # the chain inputs are the point of a run_dir case — say plainly which ones the freeze actually saw,
    # so a case that silently froze the degraded path is visible at freeze time, not months later.
    print(
        f"[{case}] chain inputs: dossier={bool(dossier_path)} risk={bool(risk_path)} "
        f"substrate_axes={sorted(substrate) if substrate else []}"
    )


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--case", choices=sorted(CASES))
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--source", default=None, help="override source evidence_package.json")
    ap.add_argument(
        "--replay-only", action="store_true", help="refreeze expected_spine from the EXISTING llm_replay (no Bedrock)"
    )
    args = ap.parse_args(argv)
    cases = sorted(CASES) if args.all else [args.case] if args.case else []
    if not cases:
        ap.error("pass --all or --case <name>")
    for c in cases:
        freeze_case(c, args.source, args.replay_only)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
