#!/usr/bin/env python
"""Regenerate the committed FULL-decision golden from the OFFLINE frozen-fixture replay.

Why a full golden: `test_data_product_schema.py::test_static_golden_conforms_if_full` validates any
committed golden that `is_full_decision()` (shared envelope + headline.skill_report). The only committed
golden was the pre-skill_report TRIMMED `kras_target_intrinsic_decision.json`, so that test SKIPPED
permanently — the static-conformance ratchet was dead. This writes a real, complete emit.

Deterministic + credential-less: it replays `fixtures/egfr.yaml` through the REAL run.py via
`test_target_intrinsic_replay.replay_decision` (the same offline path CI exercises), so the golden can be
regenerated by anyone with no S3 access:

    pixi run python skills/target-intrinsic/tests/freeze_golden_decision.py

Re-run it after any change to the emitted spine / headline (then commit the diff — that diff IS the
review artifact for an output-shape change). Refreeze `fixtures/egfr.yaml` FIRST (freeze_fixture.py,
needs AWS_PROFILE=cbg) when the upstream reader data is what changed.

The filename intentionally sorts AFTER `kras_target_intrinsic_decision.json`: skills/conftest.py's shared
`eg_decision` fixture takes `sorted(glob("*decision*.json"))[0]`, and test_evidence_graph.py's ground
truth is the KRAS fixture.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL_DIR = HERE.parent

DEFAULT_OUT = HERE / "fixtures" / "target_intrinsic_egfr_full_decision.json"


def _replay_module():
    """Import the replay test module by path (it owns the monkeypatched-dispatcher wiring)."""
    spec = importlib.util.spec_from_file_location("_ti_replay", HERE / "test_target_intrinsic_replay.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    mod = _replay_module()
    with tempfile.TemporaryDirectory() as td:
        decision = mod.replay_decision(Path(td))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(decision, indent=2, sort_keys=True) + "\n")

    from _skills_common.data_product_contract import is_full_decision

    ok = is_full_decision(decision)
    print(
        f"wrote {out} ({out.stat().st_size / 1024:.0f}K) — full_decision={ok}, "
        f"cards={len(decision.get('cards') or [])}, headline_keys={len(decision.get('headline') or {})}"
    )
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
