"""build_summary_field_types.py — a committed STRUCTURAL type partition of the summary fields.

The 46 generated schemas/methods/*.summary.schema.json already carry each summary field's JSON type
(and its enum, where declared), harvested from the emitted corpus. This builder rolls those up into
one flat, greppable, diffable snapshot — coverage/summary_field_types.yaml — mapping every
(card, field) to a structural type class:

    categorical | numeric | boolean | record | array | string | unknown

WHY this is STRUCTURAL, not editorial: the class is what a field *is* (a number, an enum token, a
container), NOT what a reader is licensed to DO with it (signal / context / provenance / display —
that editorial disposition is the skills-side field_disposition ledger + projection, a separate
axis). Naming it `summary_field_types`, not `field_disposition`, keeps the two axes from being
conflated. Its value: the skills-side projection can only classify fields SALIENCE_SPECS describes;
this partition types every field the generated schemas cover (~2k pairs), filling that gap.

Reads only the COMMITTED generated schemas, so --self-check runs on the credential-less CI runner
(no corpus needed). Mirrors build_rule_role_partition.py: a committed snapshot + a --self-check mode
that fails on drift.

  python validators/build_summary_field_types.py               # regenerate the snapshot
  python validators/build_summary_field_types.py --self-check  # CI: fail if the snapshot drifted
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO / "schemas" / "methods"
PARTITION_PATH = REPO / "coverage" / "summary_field_types.yaml"

TYPE_CLASSES = ("categorical", "numeric", "boolean", "record", "array", "string", "unknown")


def _normalize_types(prop: dict) -> set[str]:
    """The declared JSON type(s) as a set with `null` stripped (every generated property is
    null-widened; the nullability is not the field's type)."""
    t = prop.get("type")
    if isinstance(t, str):
        types = {t}
    elif isinstance(t, list):
        types = set(t)
    else:
        types = set()
    types.discard("null")
    return types


def classify_property(prop: dict) -> str:
    """One summary field's structural type class from its generated-schema property.

    enum-ness dominates: a field with a declared value vocabulary is `categorical` whatever its base
    JSON type (an enum of strings, or of the widened key type). Otherwise the base JSON type decides.
    """
    if prop.get("enum"):
        return "categorical"
    types = _normalize_types(prop)
    if not types:
        return "unknown"
    if types & {"number", "integer"}:
        return "numeric"
    if "boolean" in types:
        return "boolean"
    if "object" in types:
        return "record"
    if "array" in types:
        return "array"
    if "string" in types:
        return "string"
    return "unknown"


def _card_id_of(schema: dict, path: Path) -> str:
    # generated schemas name the card in $id / title; fall back to the filename stem.
    return schema.get("x_card_id") or path.name[: -len(".summary.schema.json")]


def compute_partition() -> dict:
    """`{counts: {class: n}, by_card: {card_id: {field: class}}}` over every generated summary
    schema. Deterministic: cards + fields sorted."""
    by_card: dict[str, dict[str, str]] = {}
    counts = {c: 0 for c in TYPE_CLASSES}
    for path in sorted(SCHEMAS_DIR.glob("*.summary.schema.json")):
        schema = json.loads(path.read_text())
        props = schema.get("properties") or {}
        card_id = _card_id_of(schema, path)
        fields: dict[str, str] = {}
        for field in sorted(props):
            cls = classify_property(props[field])
            fields[field] = cls
            counts[cls] += 1
        if fields:
            by_card[card_id] = fields
    return {
        "counts": counts,
        "n_cards": len(by_card),
        "n_fields": sum(counts.values()),
        "by_card": dict(sorted(by_card.items())),
    }


def render(partition: dict) -> str:
    header = (
        "# GENERATED by validators/build_summary_field_types.py — do not hand-edit.\n"
        "# Structural type partition of the generated summary-schema fields (categorical/numeric/\n"
        "# boolean/record/array/string/unknown). NOT the editorial signal/context/provenance/display\n"
        "# disposition (that is skills-side). --self-check gates drift.\n"
    )
    return header + yaml.safe_dump(partition, sort_keys=False, width=100)


def self_check() -> tuple[bool, list[str]]:
    if not PARTITION_PATH.exists():
        return False, [f"missing {PARTITION_PATH.name} — run without --self-check to generate it"]
    committed = yaml.safe_load(PARTITION_PATH.read_text()) or {}
    fresh = compute_partition()
    errs: list[str] = []

    c_by, f_by = committed.get("by_card") or {}, fresh["by_card"]
    for card in sorted(set(c_by) - set(f_by)):
        errs.append(f"stale card {card!r}: snapshot names a card with no generated schema")
    for card in sorted(set(f_by) - set(c_by)):
        errs.append(f"missing card {card!r}: a generated schema is not in the snapshot — regenerate")
    for card in sorted(set(c_by) & set(f_by)):
        cf, ff = c_by[card], f_by[card]
        for field in sorted(set(cf) - set(ff)):
            errs.append(f"stale field {card}.{field!r}: no longer in the generated schema")
        for field in sorted(set(ff) - set(cf)):
            errs.append(f"missing field {card}.{field!r}: in the generated schema, absent from snapshot")
        for field in sorted(set(cf) & set(ff)):
            if cf[field] != ff[field]:
                errs.append(f"drift {card}.{field}: snapshot {cf[field]!r} != computed {ff[field]!r}")

    if committed.get("counts") != fresh["counts"]:
        errs.append(f"counts drift: snapshot {committed.get('counts')} != computed {fresh['counts']}")
    return (not errs), errs


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--self-check", action="store_true", help="CI-safe: fail if the committed snapshot drifted")
    args = ap.parse_args(argv)

    if args.self_check:
        ok, errs = self_check()
        print("build_summary_field_types.py --self-check:")
        for e in errs:
            print(f"  ERROR: {e}")
        print("  OK" if ok else f"  {len(errs)} problem(s)")
        return 0 if ok else 1

    partition = compute_partition()
    PARTITION_PATH.parent.mkdir(parents=True, exist_ok=True)
    PARTITION_PATH.write_text(render(partition))
    print(f"wrote {PARTITION_PATH.relative_to(REPO)}: {partition['n_fields']} fields / {partition['n_cards']} cards")
    print(f"  counts: {partition['counts']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
