# target-archetype — finalized data product

The **I/O contract**: data wired IN, package emitted OUT, what is locked. This is an **auxiliary
(non-fan-out) skill**: a verdict-INERT, META / reduction-stage **companion-classifier**, not a
target-profile fan-out member and not a nomination gate. Logic + history live in SKILL.md / run.py /
`_skills_common/archetype_core.py`; this file is the data-product spec.

| | |
|---|---|
| **Skill** | `target-archetype` · v0.6.0 |
| **Contract version** | 1.0.0 (emitted-output schema; versioned independently — see §4) |
| **Role** | `descriptive` — **VERDICT-INERT** companion. It never nominates and never gates: ∉ target-profile `_SHORT_TO_GATE`, never wired into a resolver `when.card_id` or the `sub_verdicts` spine. It *describes* the collected cross-skill evidence as a soft phenotype landscape — it is **NOT a classifier and NOT a gate** |
| **Verdict field** | **none** — `verdict` is literal `null` by design (governance: companion, never a gate). The classification surface is a SOFT phenotype MIXTURE (`companion.soft_membership`, a convex distribution over curated anchors — never a hard label) + the verdict-inert `companion.archetype_confidence_caveat` |
| **Output shape** | **bespoke `doc`** (`companion.json`) — **NOT** the fan-out `decision` envelope: no `run_health`, no `headline.skill_report` spine, no top-level `provenance` / `generated_at`. This is why it needs a bespoke `.emit.` schema, not the generated `.decision.` envelope |
| **Emitted schema** | `target-contracts/schemas/skills/target-archetype.emit.schema.json` (**HAND-AUTHORED** bespoke aux contract — note the `.emit.` suffix; NOT generated by `gen_skill_output_schemas.py`, and it carries **no pin**) |
| **Conformance target** | the **FRESH in-process emit** — the real `scripts/run.py` over a minimal `--full-package` fixture tree (offline + deterministic; the skill ships `atlas/atlas.json`), via `tests/test_data_product_schema.py`. No hand-frozen decision fixture to go stale |

---

## 1. Inputs — CARDLESS (reads no data-catalog cards)

**LIVE.** A META layer: it derives no evidence of its own and reads no cards (`composition.cards_used: []`,
`rules_scope: []`). Its two inputs are:

| input | source | role |
|---|---|---|
| frozen atlas | `atlas/atlas.json` (feature_order · mu/sd · frozen PCA embedding · curated anchors · axis_ref · soft_labels · rule_fingerprints; n=213 reference targets) | the reference space the query is positioned against |
| composed claim_vectors | the OTHER wired sub-skills' `synthesis_facet.claim_vector` (read from a `target-profile --full-package` run tree: `subskills/*/package.json` + `nomination.json`) | the point being embedded (ordinal-encoded via the one shared vectoriser) |

The atlas is a **FROZEN artifact** (re-frozen only after a validated substrate change via
`scripts/build_atlas.py`); the emit is byte-stable otherwise.

---

## 2. Coverage & capability ceilings (contractual)

- **VERDICT-INERT, never a gate:** `verdict` is `null` and stays `null`. It attaches like the other
  reduction-stage facets (fragility / heterogeneity) and is byte-stable on the recommendation. It never
  mints a nomination.
- **Soft mixture, NEVER a hard label:** `phenotype_mixture` / `soft_membership` is a convex membership to
  the curated canonical anchors (a *distribution* over phenotypes). There is deliberately no
  `predicted_label` / `archetype` single-label field.
- **Reference-panel label circularity:** anchors are curated canonical exemplars; panel labels are
  provisional and partly circular (clinical antigens; cards designed from the same biology). An analog
  whose curated label is `"?"` shows the DATA-DERIVED soft label with a trailing `~` and
  `label_is_derived: true`. Surfaced verdict-INERT via `archetype_confidence_caveat` (3-tier:
  `validated_canonical_anchor` false-demote guard · `phenotype_mixture_low_stability_or_missingness_distorted`
  · `analog_or_label_circular`).
- **fusion_driver anchor DEFERRED:** not active in the frozen atlas, and withheld by DECLARATION rather than
  by absent exemplars — 2 of its 5 members are in the corpus, so `build_atlas.DEFERRED_ANCHORS` is the only
  thing keeping it out. Activating it bleeds RTK-ness: re-measured 2026-09-14 at n=504, **42 non-member
  targets take `fusion_driver` as their DOMINANT phenotype, 40 of them with no FUS evidence at all**, and
  precision against the FUS column is 7%. The cause is the frozen feature space (strong FUS is 2 of 176
  columns, below its uniform share of embedding influence), not the exemplar set, so it stays deferred until
  the fusion signal is separable — re-check with `scripts/anchor_separation_test.py`, never from memory,
  because the p90 bar moves with corpus size. **Consumer-visible effect:** no corpus row can ever carry a
  `fusion_driver` soft label, so a genuine fusion driver reads as `amp_driver`/`expression_surface`/
  `immune_checkpoint` instead. That is a KNOWN blind spot, not a claim that the phenotype is absent.
- **D1 nomination-readiness score ORIENTS, never nominates:** its per-archetype weights are ILLUSTRATIVE
  (SHOWN, not learned) — surfaced verdict-INERT via `scorecard_confidence_caveat` (citing the RETIRED,
  maturity-confounded outcome-trained D2/D3 approval-propensity score).

---

## 3. Emitted output

`output_shape: data_package`, but the payload is a **bespoke `doc`** written to `companion.json` (not the
standard `write_package` decision tree). Top-level keys:
`skill · skill_version · target · indication · verdict(=null) · companion · nomination_scorecard`
(+ optional `literature_synthesis` with `--literature`, `llm_synthesis` with `--synthesize`; both are
verdict-INERT LLM lanes and are **not** part of the plain conformance emit). There is **NO** `run_health`,
**NO** `headline.skill_report`, **NO** top-level `provenance` / `generated_at`.

Contractual: identity (`skill` const `target-archetype`), `verdict: null`, `companion.verdict: null`,
`nomination_scorecard.verdict: null`, and the classification vocabularies — the anchor-label set (the 8
base labels ± the derived `~` suffix, or `?`) and the confidence-caveat `reason` / `tier` enums. The
numeric payload (`soft_membership`, `missingness`, `mixture_uncertainty`, `novelty`, `rule_precedent`,
and the `nomination_scorecard` internals) is schema-OPEN.

---

## 4. Contract & versioning (what is locked)

Pinned by the **HAND-AUTHORED**, self-contained `target-archetype.emit.schema.json` (NOT generated, no
pin — a bespoke aux contract, `additionalProperties: true` at every level so the numeric internals can
evolve within a contract major):
- **required** top-level `[skill, skill_version, target, verdict, companion, nomination_scorecard]`
  (`indication` is nullable, not required);
- `skill` const · `verdict: null` · `companion.verdict: null` · `nomination_scorecard.verdict: null`;
- `anchor_label` vocabulary (8 base labels ± optional trailing `~` | `?`; corrected in
  target-contracts#657 to admit the derived soft labels the companion emits);
- `confidence_caveat` `reason` ∈ {`validated_canonical_anchor`,
  `phenotype_mixture_low_stability_or_missingness_distorted`, `analog_or_label_circular`, null} · `tier` ∈
  {`milder`, `sharp`, null}.

CI: the FRESH in-process emit conformance (`tests/test_data_product_schema.py`, **CI-fail-not-skip** on an
unresolvable schema), schema well-formedness, the cross-skill coverage ratchet
(`skills/tests/test_data_product_lock_coverage.py`), and the target-contracts schema meta-test. Change
policy: promote a numeric field to contractual → add a named property + minor bump; rename a vocabulary
term → coordinate the hand-authored schema edit + major bump.

## 5. Known gaps & notes (non-blocking)

- **CARDLESS** → no card-staleness surface; the staleness guard is the atlas re-projection /
  vocabulary-drift check (`scripts/atlas_health.py` + `archetype_core.vocabulary_drift`), not a card ledger.
- **Bespoke, not fan-out:** deliberately has no `skill_report` / `headline_block` / `run_health` — adding
  them would misrepresent it as a decision. The `.emit.` (not `.decision.`) schema encodes this.
- **Two optional LLM lanes** (`--literature` / `--synthesize`) attach `literature_synthesis` /
  `llm_synthesis` (schema type `object | null`); they need Bedrock and are excluded from the plain
  conformance emit (verdict-INERT — this layer has no verdict to move).
- The bespoke schema was corrected in target-contracts#657 (enum → pattern) so the `~`-suffixed
  data-derived soft labels in `nearest_analogs` validate.
