#!/usr/bin/env python3
"""Generate the self-contained per-skill emitted-output decision schemas.

House style is self-contained schemas (no cross-file / network $ref). To keep authoring DRY, the
SHARED spine (skill_report.schema.json) + envelope (skill_decision.schema.json) are the canonical
SOURCE, and each per-skill decision schema is GENERATED by inlining them as `$defs` and merging the
skill's thin pins (schemas/_skill_output/pins/<skill>.pins.json):

    schemas/skills/<skill>.decision.schema.json   (GENERATED, self-contained, committed)

Usage:
    python validators/gen_skill_output_schemas.py            # (re)write all per-skill schemas
    python validators/gen_skill_output_schemas.py --check    # CI: fail if committed != regenerated

The --check mode is the in-sync ratchet: a hand-edit of a generated file, or an un-regenerated edit
to the spine/envelope/pins, fails CI.
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

SCHEMAS = Path(__file__).resolve().parents[1] / "schemas"
SPINE = SCHEMAS / "skill_report.schema.json"
ENVELOPE = SCHEMAS / "skill_decision.schema.json"
PINS_DIR = SCHEMAS / "_skill_output" / "pins"
OUT_DIR = SCHEMAS / "skills"
BASE_ID = "https://github.com/takeda-rnd/rnd-computational-biology-oncology-target-contracts/schemas/"
_META_KEYS = ("$schema", "$id", "$comment", "title", "version")


def _load(p: Path) -> dict:
    return json.loads(p.read_text())


def _as_def(doc: dict) -> dict:
    """Strip file-level meta so an embedded $defs entry does not create a new $id resolution scope."""
    d = copy.deepcopy(doc)
    for k in _META_KEYS:
        d.pop(k, None)
    return d


def _rewrite_spine_ref(node):
    """Rewrite the envelope's cross-file `$ref: skill_report.schema.json` to the embedded `#/$defs/skill_report`."""
    if isinstance(node, dict):
        if node.get("$ref") == "skill_report.schema.json":
            node["$ref"] = "#/$defs/skill_report"
        for v in node.values():
            _rewrite_spine_ref(v)
    elif isinstance(node, list):
        for v in node:
            _rewrite_spine_ref(v)
    return node


def build(skill: str, spine: dict, envelope: dict, pins: dict) -> dict:
    version = envelope.get("version", "1.0.0")
    defs = {"skill_report": _as_def(spine), "skill_decision": _rewrite_spine_ref(_as_def(envelope))}
    defs.update(copy.deepcopy(pins.get("$defs") or {}))
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"{BASE_ID}skills/{skill}.decision.schema.json",
        "title": f"{skill} decision",
        "version": version,
        "$comment": (
            f"GENERATED by validators/gen_skill_output_schemas.py from skill_report.schema.json + "
            f"skill_decision.schema.json + _skill_output/pins/{skill}.pins.json — DO NOT EDIT BY HAND. "
            f"Self-contained (no cross-file $ref). Contract v{version}."
        ),
        "$defs": defs,
        "allOf": [{"$ref": "#/$defs/skill_decision"}, copy.deepcopy(pins["pins"])],
    }


def _pin_files() -> list[Path]:
    return sorted(PINS_DIR.glob("*.pins.json"))


def generate_all(check: bool) -> int:
    spine, envelope = _load(SPINE), _load(ENVELOPE)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    drift = []
    for pin_path in _pin_files():
        skill = pin_path.name[: -len(".pins.json")]
        pins = _load(pin_path)
        built = build(skill, spine, envelope, pins)
        rendered = json.dumps(built, indent=2, ensure_ascii=False) + "\n"
        out = OUT_DIR / f"{skill}.decision.schema.json"
        if check:
            current = out.read_text() if out.exists() else "<absent>"
            if current != rendered:
                drift.append(skill)
        else:
            out.write_text(rendered)
            print(f"wrote {out.relative_to(SCHEMAS.parent)}")
    if check and drift:
        print(f"OUT OF SYNC (regenerate: python validators/gen_skill_output_schemas.py): {drift}", file=sys.stderr)
        return 1
    if check:
        print(f"in sync: {len(_pin_files())} per-skill schema(s)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if committed != regenerated (CI)")
    args = ap.parse_args()
    return generate_all(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
