#!/usr/bin/env python3
"""render-evidence-package — Stage-1 markdown renderer for evidence_package.json.

Consumes an evidence_package matching evidence_package.schema.json and produces a
human-readable Stage-1 markdown rendering. This is the only renderer that ships in
iter-1b; HTML (Stage 2), PowerPoint (Stage 3), decision memo (Stage 3+), and
interactive UI (Stage 4) are deferred.

The renderer is intentionally simple: it walks the evidence_package's top-level
sections and emits each as a markdown block. NO new synthesis, NO new interpretation,
NO new computation — the renderer is a pure formatter of upstream artifacts. Per
the layer-distinction discipline, the renderer adds nothing to the dashboard,
interpretation, or inference layers; it surfaces what they produced.

Usage:
    python -m scripts.render_markdown \
        --evidence-package /path/to/evidence_package.json \
        --out /path/to/dashboard.md

Library:
    from scripts.render_markdown import render_evidence_package
    md = render_evidence_package(ep_dict)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional

import click


def render_evidence_package(ep: dict) -> str:
    """Render an evidence_package dict to a markdown string.

    The renderer dispatches on axis_resolution status (via dashboard_spec_ref) to
    produce either a full dashboard (resolved case) or a refusal page (unresolved).
    """
    target_symbol = ep["context"]["target"]["symbol"]
    indication = ep["context"]["indication"]["oncotree_code"]

    sections = []

    # ===== Title =====
    sections.append(f"# Evidence Package: {target_symbol} in {indication}")
    sections.append("")
    sections.append(f"_Package ID: `{ep['package_id']}` · Framework version: {ep['framework_version']}_")
    sections.append("")

    # ===== Refusal case — empty cards array means axis was unresolved =====
    if not ep.get("cards"):
        sections.extend(_render_refusal_page(ep))
        return "\n".join(sections) + "\n"

    # ===== Executive summary (synthesis headline) =====
    syn = ep.get("synthesis", {}) or {}
    sections.append("## Executive Summary")
    sections.append("")
    sections.append(f"**{syn.get('headline', '(no headline produced)')}**")
    sections.append("")
    if syn.get("caveats_summary"):
        sections.append(f"_Caveats_: {syn['caveats_summary']}")
        sections.append("")

    # ===== Per-modality fit assessment =====
    fit = syn.get("modality_fit_assessment", []) or []
    if fit:
        sections.extend(_render_modality_fit_table(fit))

    # ===== Table of contents =====
    sections.extend(_render_toc(ep, fit))

    # ===== Governance block =====
    sections.extend(_render_governance(ep))

    # ===== Per-card panels =====
    sections.append("## Card Evidence")
    sections.append("")
    for card in ep["cards"]:
        sections.extend(_render_card_panel(card))

    # ===== Failed-cards section (explicit accounting for n_cards_failed) =====
    sections.extend(_render_failed_cards_section(ep))

    # ===== Provenance footer =====
    sections.extend(_render_provenance_footer(ep))

    return "\n".join(sections) + "\n"


# ============================================================================
# Sub-renderers
# ============================================================================

def _render_refusal_page(ep: dict) -> list[str]:
    """Render the refusal page when the framework cannot proceed (axis unresolved,
    modality incompatible, etc.). This is the negative-control discipline rendered
    user-facing."""
    syn = ep.get("synthesis", {}) or {}
    sections = []
    sections.append("## ⚠️ Framework Refused to Evaluate")
    sections.append("")
    sections.append(syn.get("headline", "The framework could not produce evidence for this target/indication."))
    sections.append("")
    if syn.get("caveats_summary"):
        sections.append("### Next Steps")
        sections.append("")
        sections.append(syn["caveats_summary"])
        sections.append("")

    # Governance still useful in refusal case (shows data_mode, release_pin)
    sections.extend(_render_governance(ep))

    # Provenance shows what WAS attempted
    sections.append("## Provenance")
    sections.append("")
    sections.append(f"- **Generated at**: `{ep.get('generated_at', 'unknown')}`")
    sections.append(f"- **Generated by**: `{ep.get('generated_by', 'unknown')}`")
    sections.append(f"- **Dashboard spec referenced**: `{ep.get('dashboard_spec_ref', 'unresolved')}`")
    sections.append("")
    return sections


FIT_ICONS = {"strong": "🟢", "moderate": "🟡", "weak": "🟠",
              "insufficient_evidence": "⚪", "not_viable": "🔴"}


def _fmt_evidence_cell(entry: dict) -> str:
    """Render the 'Primary Evidence' cell of the modality-fit table.

    Distinguishes the EG4 dominant-signal path (worth the loudest cell) from the
    ratio-based path. Avoids the misleading 'X/N primary positive' phrasing when
    the dominant rule fired — the underlying decision logic is 'one dominant call
    is sufficient', so the cell should reflect that.
    """
    dominant = entry.get("dominant_hits", []) or []
    positive = entry.get("primary_cards_positive_count", 0)
    in_scope = entry.get("primary_cards_in_scope", 0)
    total = entry.get("primary_cards_total", in_scope)
    if dominant:
        n = len(dominant)
        return f"**{n} dominant positive** (sufficient) — {positive}/{in_scope} of {total} total"
    if entry.get("fit_level") == "not_viable":
        return "—"
    if entry.get("fit_level") == "insufficient_evidence":
        return f"0/{in_scope} in scope ({total} total)"
    return f"{positive}/{in_scope} primary positive ({total} total)"


def _render_modality_fit_table(fit: list[dict]) -> list[str]:
    sections = []
    sections.append("## Modality Fit Assessment")
    sections.append("")

    # Collapse 1-modality table to an inline summary line.
    if len(fit) == 1:
        entry = fit[0]
        modality = entry.get("modality", "?")
        fit_level = entry.get("fit_level", "?")
        fit_icon = FIT_ICONS.get(fit_level, "")
        ev = _fmt_evidence_cell(entry)
        killers = entry.get("killer_conditions_hit", []) or []
        killer_line = (
            f" Killer conditions: {'; '.join(killers)}." if killers else ""
        )
        question = entry.get("headline_decision_question", "")
        sections.append(
            f"**{modality}** fit: {fit_icon} **{fit_level}**. "
            f"Evidence: {ev}.{killer_line}"
        )
        if question:
            sections.append("")
            sections.append(f"_Decision question: {question}_")
        sections.append("")
        return sections

    # >=2 modalities: render the table as usual
    sections.append("| Modality | Fit | Primary Evidence | Killer Conditions Hit |")
    sections.append("|---|---|---|---|")
    for entry in fit:
        modality = entry.get("modality", "?")
        fit_level = entry.get("fit_level", "?")
        killers = entry.get("killer_conditions_hit", []) or []
        killers_cell = "none" if not killers else f"{len(killers)} hit"
        fit_icon = FIT_ICONS.get(fit_level, "")
        sections.append(
            f"| **{modality}** | {fit_icon} {fit_level} | {_fmt_evidence_cell(entry)} | {killers_cell} |"
        )
    sections.append("")

    sections.append("### Decision Questions Asked")
    sections.append("")
    for entry in fit:
        modality = entry.get("modality", "?")
        question = entry.get("headline_decision_question", "")
        sections.append(f"- **{modality}**: _{question}_")
    sections.append("")
    return sections


def _render_toc(ep: dict, fit: list[dict]) -> list[str]:
    """Render a table of contents linking to each non-excluded card section + standard blocks."""
    sections = ["## Contents", ""]
    sections.append("- [Modality Fit Assessment](#modality-fit-assessment)")
    sections.append("- [Governance](#governance)")
    sections.append("- [Card Evidence](#card-evidence)")
    for card in ep.get("cards", []):
        if card.get("excluded_by_applies_when"):
            continue
        cid = card.get("card_id", "")
        anchor = cid.replace("_", "-")
        interp = card.get("interpretation_call", "")
        sections.append(f"  - [`{cid}`](#-{anchor}--{interp.lower().replace(' ', '-').replace('—', '').replace('--', '-')[:40]}) — _{interp}_")
    sections.append("- [Failed Cards](#failed-cards)")
    sections.append("- [Provenance Footer](#provenance-footer)")
    sections.append("")
    return sections


def _render_failed_cards_section(ep: dict) -> list[str]:
    """Explicit accounting for n_cards_failed. The envelope drops failed cards (they
    return None and are skipped in phase-2). Stakeholders reading 'n_cards_failed: 3'
    but seeing no failed entries in Card Evidence get confused. This section lists
    what was attempted-and-missing so the count becomes auditable."""
    gov = ep.get("governance", {}) or {}
    vs = gov.get("validation_summary", {}) or {}
    n_failed = vs.get("n_cards_failed", 0)
    if not n_failed:
        return []

    sections = []
    sections.append("## Failed Cards")
    sections.append("")
    sections.append(
        f"{n_failed} card(s) were attempted but did not produce evidence in this run. "
        f"In live mode this typically means the card has no live dispatcher registered yet "
        f"(framework coverage gap, not a data issue). Affected cards are dropped from the "
        f"per-card panels above; the validation_summary count below reflects the gap."
    )
    sections.append("")
    sections.append(
        "_Likely causes_: (a) missing live dispatcher in `_live_readers.CARD_DISPATCHERS`, "
        "(b) method module not importable, (c) all input data sources returned errors."
    )
    sections.append("")
    return sections


def _render_governance(ep: dict) -> list[str]:
    gov = ep.get("governance", {}) or {}
    vs = gov.get("validation_summary", {}) or {}
    sections = []
    sections.append("## Governance")
    sections.append("")
    sections.append(f"- **Data mode**: `{gov.get('data_mode', 'unknown')}`")
    sections.append(f"- **Release pin**: `{gov.get('release_pin', 'unpinned')}`")
    if gov.get("lockfile_ref"):
        sections.append(f"- **Lockfile**: `{gov['lockfile_ref']}`")

    concur = gov.get("concurrence")
    if concur:
        sections.append(
            f"- **Concurrence**: {concur.get('state', '?')} "
            f"(reviewer: `{concur.get('reviewer_id', '?')}`)"
        )
    else:
        sections.append("- **Concurrence**: _not recorded_ (exploratory grade only — NOT citable in nominations)")

    sections.append("")
    sections.append("### Validation Summary")
    sections.append("")
    sections.append(f"- Cards attempted: **{vs.get('n_cards_attempted', 0)}**")
    sections.append(f"- Passed: **{vs.get('n_cards_passed', 0)}**")
    sections.append(f"- Passed with warnings: **{vs.get('n_cards_passed_with_warnings', 0)}**")
    sections.append(f"- Failed: **{vs.get('n_cards_failed', 0)}**")
    sections.append(f"- Excluded by `applies_when`: **{vs.get('n_cards_excluded_by_applies_when', 0)}**")
    sections.append("")
    return sections


def _render_card_panel(card: dict) -> list[str]:
    """Render a single card_present or card_excluded entry."""
    sections = []
    card_id = card.get("card_id", "unknown-card")

    # Excluded card → render a stub with reason
    if card.get("excluded_by_applies_when"):
        sections.append(f"### ⏸️ `{card_id}` — excluded")
        sections.append("")
        sections.append(f"_Excluded by `applies_when` at compose time._")
        sections.append("")
        sections.append(f"**Reason**: {card.get('exclusion_reason', '(no reason provided)')}")
        sections.append("")
        sections.append("---")
        sections.append("")
        return sections

    # Present card
    interp = card.get("interpretation_call", "uninterpreted")
    val_state = card.get("validation_state", "?")
    state_icon = {"pass": "✓", "passed_with_warnings": "⚠"}.get(val_state, "?")
    sections.append(f"### {state_icon} `{card_id}` — _{interp}_")
    sections.append("")

    # Figures block — embed each card.figures[] entry as a markdown image reference.
    # Primary figure rendered first; alternate figures collapsed into a <details> block.
    figures = card.get("figures", []) or []
    if figures:
        primary = [f for f in figures if f.get("primary")]
        alternates = [f for f in figures if not f.get("primary")]
        for f in primary:
            alt = f.get("type", f.get("id", "figure"))
            sections.append(f"![{alt}]({f['path']})")
            sections.append("")
        if alternates:
            sections.append("<details><summary>Alternate views</summary>")
            sections.append("")
            for f in alternates:
                alt = f.get("type", f.get("id", "figure"))
                sections.append(f"![{alt}]({f['path']})")
                sections.append("")
            sections.append("</details>")
            sections.append("")

    # Summary block — scalars in a YAML block, lists-of-dicts pulled out as markdown
    # tables for readability. Internal-state keys (underscore-prefixed) are hidden.
    summary = card.get("summary", {}) or {}
    if summary:
        scalars = {}
        tabular = []
        for k, v in summary.items():
            if k.startswith("_"):
                continue  # hide framework-internal keys
            if _is_tabular_list(v):
                tabular.append((k, v))
            else:
                scalars[k] = v

        if scalars:
            sections.append("**Summary**:")
            sections.append("")
            sections.append("```yaml")
            for k, v in scalars.items():
                sections.append(f"{k}: {_format_yaml_value(v)}")
            sections.append("```")
            sections.append("")
        for k, rows in tabular:
            sections.append(f"**{k}**:")
            sections.append("")
            if k in _PANORAMA_RECORD_FIELDS:
                # Subgroup panorama — render with evidence_state trichotomy so a
                # measured negative reads differently from an underpowered unknown.
                sections.extend(_render_subgroup_panorama_table(rows))
            else:
                sections.extend(_render_list_of_dicts_as_table(rows))
            sections.append("")

    # Warning IDs
    warnings = card.get("warning_ids", []) or []
    if warnings:
        sections.append(f"**Warnings**: {', '.join(f'`{w}`' for w in warnings)}")
        sections.append("")

    # Caveats
    caveats = card.get("caveats", []) or []
    if caveats:
        sections.append("**Caveats**:")
        sections.append("")
        for c in caveats:
            sections.append(f"- {c}")
        sections.append("")

    # Provenance
    prov = card.get("provenance", {}) or {}
    method_calls = prov.get("method_calls", []) or []
    input_manifests = prov.get("input_manifest_ids", []) or []
    if method_calls or input_manifests:
        sections.append("<details><summary>Provenance</summary>")
        sections.append("")
        if method_calls:
            sections.append("Method calls:")
            for mc in method_calls:
                sections.append(f"- `{mc.get('method', '?')}@{mc.get('git_sha', '?')}`")
        if input_manifests:
            sections.append("")
            sections.append(f"Input manifests: {', '.join(f'`{m}`' for m in input_manifests)}")
        sections.append("")
        sections.append("</details>")
        sections.append("")

    sections.append("---")
    sections.append("")
    return sections


_FLOAT_PRECISION = 3


def _format_yaml_value(v) -> str:
    """Format a summary value for inclusion in a markdown YAML-block.

    Floats rounded to _FLOAT_PRECISION decimal places — humans don't read at 15
    significant digits, and the precision suggests false confidence in numbers
    that are estimates from finite-sample statistics. Provenance / manifest.yaml
    still carries full-precision values for audit; this is the display layer.
    """
    if isinstance(v, float):
        return f"{v:.{_FLOAT_PRECISION}f}"
    if isinstance(v, list):
        return json.dumps(v, default=str)
    if isinstance(v, dict):
        return json.dumps(v, default=str)
    if isinstance(v, str):
        return v
    return str(v)


def _is_tabular_list(v) -> bool:
    """Return True iff v is a non-empty list of dicts. Used to lift verbose
    list-of-dicts summary fields (e.g. top_dependent_lineages, hotspot_frequencies)
    out of the YAML block into their own table."""
    if not isinstance(v, list) or not v:
        return False
    if not all(isinstance(item, dict) for item in v):
        return False
    return True


def _render_list_of_dicts_as_table(rows: list[dict]) -> list[str]:
    """Render a list of dicts as a markdown table. Columns are the union of all
    keys (preserving first-seen order). Float values rounded to _FLOAT_PRECISION."""
    cols = []
    seen = set()
    for r in rows:
        for k in r.keys():
            if k not in seen:
                cols.append(k)
                seen.add(k)
    lines = []
    lines.append("| " + " | ".join(cols) + " |")
    lines.append("|" + "|".join(["---"] * len(cols)) + "|")
    for r in rows:
        cells = []
        for k in cols:
            v = r.get(k, "")
            if isinstance(v, float):
                cells.append(f"{v:.{_FLOAT_PRECISION}f}")
            elif isinstance(v, (list, dict)):
                cells.append(json.dumps(v, default=str))
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")
    return lines


# Subgroup-panorama record fields (2026-07-16). Rendered with evidence_state
# awareness rather than the generic list-of-dicts table. Both spellings in use.
_PANORAMA_RECORD_FIELDS = {"per_subgroup_metrics", "per_stratum_metrics"}

# evidence_state → (icon, label) for the descriptive trichotomy. A `measured`
# negative (real value on a floor-clearing cohort) is a trusted finding; an
# `underpowered` / `absent` row is an UNKNOWN and must read differently.
_EVIDENCE_STATE_BADGE = {
    "measured": ("●", "measured"),
    "underpowered": ("◐", "underpowered"),
    "absent": ("○", "absent"),
}
_SUBGROUP_N_FLOOR = 30  # mirrors methods/subgroup_common/panorama.py SUBGROUP_N_FLOOR


def _render_subgroup_panorama_table(rows: list[dict]) -> list[str]:
    """Render a per-subgroup panorama with the evidence_state trichotomy made legible.

    Descriptive-only: enumerates EVERY stratum row (positive AND negative). The
    evidence_state column distinguishes a trusted `measured` value (floor-cleared)
    from an `underpowered` / `absent` UNKNOWN. Underpowered rows are flagged
    inline with their n vs the floor so a reader never mistakes an unknown for a
    confirmed negative — and (per the admissibility rule) never lifts an
    underpowered number into a comparative claim.

    `stratum` and `evidence_state` are pinned as the first two columns; the rest
    follow first-seen order. Internal (underscore-prefixed) keys are hidden.
    """
    if not rows:
        return ["_(no subgroup rows)_"]

    # Column order: stratum, evidence_state, then the rest (first-seen), no _keys.
    lead = [c for c in ("stratum", "evidence_state") if any(c in r for r in rows)]
    cols = list(lead)
    for r in rows:
        for k in r.keys():
            if k.startswith("_") or k in cols:
                continue
            cols.append(k)

    lines = ["| " + " | ".join(cols) + " |",
             "|" + "|".join(["---"] * len(cols)) + "|"]
    for r in rows:
        state = r.get("evidence_state")
        cells = []
        for k in cols:
            if k == "evidence_state":
                icon, label = _EVIDENCE_STATE_BADGE.get(state, ("?", str(state)))
                # Flag underpowered rows inline with n vs floor.
                if state == "underpowered":
                    n = r.get("subgroup_n")
                    label = f"underpowered (n={n}<{_SUBGROUP_N_FLOOR})" if n is not None else "underpowered"
                cells.append(f"{icon} {label}")
                continue
            v = r.get(k, "")
            if isinstance(v, float):
                cells.append(f"{v:.{_FLOAT_PRECISION}f}")
            elif isinstance(v, (list, dict)):
                cells.append(json.dumps(v, default=str))
            else:
                cells.append(str(v))
        lines.append("| " + " | ".join(cells) + " |")

    # Legend + admissibility note — the descriptive payoff made explicit.
    lines.append("")
    lines.append(
        "_● measured (n≥{floor}, trusted — a real negative is as informative as a "
        "positive) · ◐ underpowered (n<{floor}, UNKNOWN — inadmissible in comparative "
        "claims) · ○ absent (no samples in this stratum). Rows tagged by source_cohort "
        "are not merged across cohorts._".format(floor=_SUBGROUP_N_FLOOR)
    )
    return lines


def _render_provenance_footer(ep: dict) -> list[str]:
    sections = []
    sections.append("## Provenance Footer")
    sections.append("")
    sections.append(f"- **Generated at**: `{ep.get('generated_at', 'unknown')}`")
    sections.append(f"- **Generated by**: `{ep.get('generated_by', 'unknown')}`")
    sections.append(f"- **Dashboard spec**: `{ep.get('dashboard_spec_ref', 'unknown')}`")
    ctx = ep.get("context", {}) or {}
    if ctx.get("subgroup_spec"):
        sections.append(f"- **Subgroup spec**: `{ctx['subgroup_spec']}`")
    sections.append(f"- **Schema version**: {ep.get('schema_version', '?')}")
    sections.append("")
    return sections


# ============================================================================
# CLI
# ============================================================================

@click.command()
@click.option("--evidence-package", "ep_path", required=True,
              type=click.Path(exists=True, dir_okay=False, path_type=Path),
              help="Path to evidence_package.json (or evidence_package.yaml).")
@click.option("--out", required=True, type=click.Path(dir_okay=False, path_type=Path),
              help="Output markdown path (typically dashboard.md).")
def main(ep_path: Path, out: Path) -> int:
    """Render an evidence_package to Stage-1 markdown."""
    with ep_path.open() as f:
        if ep_path.suffix.lower() in (".yaml", ".yml"):
            import yaml as _yaml
            ep = _yaml.safe_load(f)
        else:
            ep = json.load(f)

    md = render_evidence_package(ep)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(md, encoding="utf-8")

    target = ep.get("context", {}).get("target", {}).get("symbol", "?")
    indication = ep.get("context", {}).get("indication", {}).get("oncotree_code", "?")
    n_cards = len(ep.get("cards", []))
    click.echo(f"=== render_markdown ===")
    click.echo(f"  evidence_package: {ep_path}")
    click.echo(f"  target/indication: {target} / {indication}")
    click.echo(f"  cards rendered:    {n_cards}")
    click.echo(f"  → wrote:           {out} ({len(md)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
